import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--root", type=str, default="/kaggle/input/sketchy", help="path to dataset")
parser.add_argument("--ckpt_path", type=str, default="", help="path to dataset")
parser.add_argument("--dataset", type=str, default="sketchy_2", help="type of dataset")
parser.add_argument("--output_dir", type=str, default="", help="output directory")
parser.add_argument("--backbone", type=str, default="ViT-B/32")
parser.add_argument("--n_ctx", type=int, default=2)
parser.add_argument("--img_ctx", type=int, default=2)
parser.add_argument("--max_size", type=int, default=224)
parser.add_argument("--prompt_depth", type=int, default=12)
parser.add_argument("--data_split", type=int, default=-1)
parser.add_argument("--prec", type=str, default="fp16")
parser.add_argument("--distill", type=str, default="cosine")
parser.add_argument("--temperature", type=float, default=0.07)
parser.add_argument("--w_triplet", type=float, default=0.8, help="loss weight for triplet")
parser.add_argument("--w_photo_skt", type=float, default=0.1, help="loss weight for photo-sketch contrastive (cross_loss)")
parser.add_argument("--w_distill", type=float, default=0.1, help="loss weight for distillation")
parser.add_argument("--w_ce", type=float, default=1.0, help="loss weight for (ce_photo + ce_sketch)")
parser.add_argument("--w_mcc", type=float, default=0.1, help="loss weight for MCC")
parser.add_argument("--w_cjs", type=float, default=0.1)
parser.add_argument("--triplet_margin", type=float, default=0.3)
parser.add_argument("--jigsaw_grid", type=int, default=2)

parser.add_argument("--lr", type=float, default=0.035)
parser.add_argument('--batch_size', type=int, default=128)
parser.add_argument('--test_batch_size', type=int, default=1024)
parser.add_argument('--epochs', type=int, default=60)
parser.add_argument('--workers', type=int, default=4)
parser.add_argument('--progress', type=bool, default=False)
parser.add_argument('--use_subset', type=bool, default=False)
parser.add_argument('--val_ratio', type=float, default=0.2)
parser.add_argument('--split_seed', type=int, default=42)
parser.add_argument('--fg_sbir', dest='fg_sbir', action='store_true')
parser.add_argument('--zero_shot', dest='fg_sbir', action='store_false')
parser.set_defaults(fg_sbir=True)

parser.add_argument('--exp_name', type=str, default='Co_prompt')

args = parser.parse_args()
